Add the assets command to the vulcan-cli
adevinta/vulcan-api pull request #106
Opened 2023-02-13 14:23 UTC by manelmontilla

This PR adds a new command to the Vulcan-cli that allows to download all the assets, or only the ones with a given asset type, to a local file.

2023-02-13 15:07 UTC, danfaizer requested changes

2023-02-13 15:07 UTC, danfaizer commented on cmd/vulcan-cli/cmd/assets.go
> +		if err != nil && errors.Is(err, fs.ErrExist) {
I believe this condition is not working as is expected by the `-f` flag.

Perhaps is easier:
```
# (if no error, file exists)
jf err == nil {
    return ErrOutputAlreadyExists
}
```
Of course there could be another issues (such as permissions, etc.).

So I would suggest a refactor on this.

2023-02-14 10:29 UTC, manelmontilla commented on cmd/vulcan-cli/cmd/assets.go
> +		if err != nil && errors.Is(err, fs.ErrExist) {
Absolutely, this is not working at all. 
I'm refactoring out the code that checks if the file exits into its own function, which is what I should have done from the beginning.

2023-02-16 17:57 UTC, jesusfcr approved these changes
Very nice!

2023-02-16 18:02 UTC, jesusfcr commented
For next releases I think it would be very useful a json export

```json
[ 
{ "id" "2222", "name":"team-name",
  "assets": [
    {"id":"www.adevinta.com","type":"hostname"},
    {"id":"https://www.adevinta.com","type":"WebAddress"}
  ]
}
]
```

As this will be very flexible to get all the info using jq

```sh
# assets of one team
cat output.json | jq '.[] | select ( .name == 'team' ) | .assets[].id'
...
```

2023-02-17 07:11 UTC, merged