feat: create tickets endpoint
adevinta/vulcan-api pull request #108
Opened 2023-02-14 13:47 UTC by seilagamo

Create a new endpoint to create tickets. This endpoint calls to vulcan-tracker to create the ticket itself.
Also, the endpoint to retrieve findings has been modified to call vulcan-tracker and get the link of an existing ticket.

Pending:
- Add testing.

2023-03-27 09:56 UTC, manelmontilla requested changes

2023-03-27 09:56 UTC, manelmontilla commented on pkg/api/service/vulcantracker.go
> +/*
I would name this file, something like: `findings_tickets.go` or just `tickets.go` in order to follow the naming conventions of the package.

2023-03-27 09:56 UTC, manelmontilla commented on pkg/common/common.go
> +func IsHttpStatusOk(status int) bool {
s/Http/HTTP

2023-03-27 09:56 UTC, manelmontilla commented on pkg/common/common.go
> +func IsHttpStatusOk(status int) bool {
In any case, I'm not sure we should create a function in the common package like this. I think that if a HTTP status is okey or not depends a lot on the concrete call to the REST service. For instance,  in this case It's not cleat to me in which cases the vulcan-tracker could return a 300 status code and consider it to be valid.

2023-03-27 09:56 UTC, manelmontilla commented on pkg/common/common.go
> +func BuildQueryFilter(filters map[string]string) string {
We should add a doc comment in exported functions.

2023-03-27 09:56 UTC, manelmontilla commented on pkg/common/common.go
> +func ParseHttpErr(statusCode int, mssg string) error {
s/Http/HTTP
Also add a doc comment as this is an exported function.

2023-03-27 09:56 UTC, manelmontilla commented on pkg/vulcantracker/vulcantracker.go
> +	IsATeamOnboardedInVulcanTracker(ctx context.Context, teamID string) bool // feature flag.
I would not place this function here. 
As I understand this package it's just a client for the vulcan-tracker component and the feature flag that enables the tracker functionality or not for a component is not independent of that component right?

2023-03-27 09:56 UTC, manelmontilla commented on pkg/vulnerabilitydb/vulnerabilitydb.go
> -
I wouldn't move these functions: `isStatusOk`, `buildFilter`, `parseErr`  to the package common.
The package common is for more lets say generics things and those functions were only used by the vulnerabilitydb client and now also by the vulcantracker, but not for the rest of the clients, for instance the scanengine. So I would prefer to repeat the code in each of the packages. Also I'm not sure the vulcantracker needs to use those functions right now. I mean the endpoints that the vulcan-tracker is calling don't use query string params and can't return 300 errors right now?

2023-03-27 11:02 UTC, seilagamo commented on README.md
> +If you are a macOS user you'll need to install `coreutils` before the following commands.
Ok, I have just uninstalled `coreutils` and executed `go generate .\...` and I have got the error:
```
_gen/gen.sh: line 12: realpath: command not found
pkg/asyncapi/vulcan.go:7: running "sh": exit status 127
```

2023-03-27 14:58 UTC, seilagamo commented on pkg/api/endpoint/findings.go
> +			// TODO: we need to decide if we should ignore errors getting tickets from vulcan-tracker
This was when I was thinking about the teams that weren't onboarded in vulcan-tracker. I forgot to refactor this part.

2023-03-30 07:46 UTC, seilagamo commented on README.md
> +If you are a macOS user you'll need to install `coreutils` before the following commands.
I added some extra information about the specific command that produces the error.

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:46 UTC, seilagamo commented on cmd/vulcan-api-cli/design/findings.go
> +var FindingTicketCreationMedia = MediaType("finding_ticketcreation", func() {
Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:47 UTC, seilagamo commented on cmd/vulcan-api-cli/design/findings.go
> +		Attribute("description", String, "The previous status for the finding referenced by the finding_id field", func() { Example("Very long desciption explaining the ticket.") })
I have removed all the not necessary fields

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:47 UTC, seilagamo commented on cmd/vulcan-api-cli/design/teams.go
> +		Attribute("is_onboarded_vulcan_tracker", Boolean, "Is Onboarded in Vulcan Tracker", func() { Example(true) }) // feature flag.
Changed!!

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:48 UTC, seilagamo commented on config.toml
> +
Changed in all toml files

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:49 UTC, seilagamo commented on pkg/api/endpoint/findings.go
> +			// TODO: we need to decide if we should ignore errors getting tickets from vulcan-tracker
Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:49 UTC, seilagamo commented on pkg/api/endpoint/vulcantracker.go
> +/*
Renamed all vulcantracker words

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:50 UTC, seilagamo commented on pkg/api/endpoint/vulcantracker.go
> +// between findings and tickets.
Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:50 UTC, seilagamo commented on pkg/api/service/vulcantracker.go
> +/*
Renamed!!

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:53 UTC, seilagamo commented on pkg/common/common.go
> +func IsHttpStatusOk(status int) bool {
I moved the functions to tickets.go and I left vulnerabilitydb.go as it was

2023-03-30 07:53 UTC, seilagamo commented on pkg/common/common.go
> +func IsHttpStatusOk(status int) bool {
Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:53 UTC, seilagamo commented on pkg/common/common.go
> +func BuildQueryFilter(filters map[string]string) string {
Added doc comments in all exported functions.
Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-03-30 07:54 UTC, seilagamo commented on pkg/vulnerabilitydb/vulnerabilitydb.go
> -
I left the file as it was before the PR.

Fixed in commit 9267f0cbf7a85be984aed7fdcf524b59d5998404

2023-04-05 12:25 UTC, manelmontilla requested changes

2023-04-05 13:51 UTC, seilagamo commented on config.toml
> +onboarded_teams = "$VULCANTRACKER_TEAMS"
Fixed in commit 5bed669a367ecd1d0e9c80aba60c5bc3480cef4b

2023-04-05 14:54 UTC, manelmontilla submitted a review, later dismissed
LGTM

2023-06-26 11:23 UTC, manelmontilla requested changes

2023-06-26 11:23 UTC, manelmontilla commented on README.md
> +|VULCANTRACKER_URL|Leave the url empty if you don't want to configurate the vulcan-tracker component|http://localhost:8085|
s/configurate/configure

2023-06-26 11:23 UTC, manelmontilla commented on _resources/config/local.toml.example
> +# leave the url empty if you don't want to configurate the vulcan-tracker component.
s/configurate/configure

2023-06-26 11:23 UTC, manelmontilla commented on contrib/dev/local-dev.toml
> +# leave the url empty if you don't want to configurate the vulcan-tracker component.
s/configurate/configure

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/endpoint/tickets.go
> +			if ticket == nil {
I wouldn't check here if the ticket is nil and return a 500.
I would modify the method [MakeEndpoints](https://github.com/adevinta/vulcan-api/blob/ddd822ad4ec93b3f640a381da3c144860f1fd92c/pkg/api/endpoint/endpoints.go#L135) so it receives a bool param `isJiraIntegrationEnabled`, and if it is false, the method will not add the `FindingTicketEndpoint`.

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/service/teams.go
> +func isATeamOnboardedInVulcanTracker(teamID string, onboardedTeams []string) bool {
I would make this function to be a method of the `vulcanitoServiceStruct` and change the implementation to something like this:
```go
if s.vulcantrackerClient == nil {
		return false
	}
	for _, team := range onboardedTeams {
		if team == teamID {
			return true
		}
	}
	return false
``` 
This way we won't need the check if the `vulcanTrackerClient` is nil before calling this function.

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/service/teams.go
> +	if s.vulcantrackerClient == nil {
If we do what I suggest in a previous comment we don't need to check if this field is nil here.

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/service/teams.go
> +		return team, nil
If we do what I suggest in a previous comment we don't need to check if this field is nil here.

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/service/teams.go
> +		return teams, nil
If we do what I suggest in a previous comment we don't need to check if this field is nil here.

2023-06-26 11:23 UTC, manelmontilla commented on pkg/api/service/tickets.go
> +	if s.vulcantrackerClient == nil {
If don't add ``CreateTicketEndpoint`` if the Jira integration is not enabled we don't need to check if this field is nil here.

2023-06-27 08:00 UTC, seilagamo commented on README.md
> +|VULCANTRACKER_URL|Leave the url empty if you don't want to configurate the vulcan-tracker component|http://localhost:8085|
Fixed in commit 3f5b3b3bac78661df03e484824e4d667ea4beadf

2023-06-27 08:01 UTC, seilagamo commented on _resources/config/local.toml.example
> +# leave the url empty if you don't want to configurate the vulcan-tracker component.
Fixed in commit 3f5b3b3bac78661df03e484824e4d667ea4beadf

2023-06-27 08:02 UTC, seilagamo commented on pkg/api/endpoint/tickets.go
> +			if ticket == nil {
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 08:02 UTC, seilagamo commented on pkg/api/service/teams.go
> +func isATeamOnboardedInVulcanTracker(teamID string, onboardedTeams []string) bool {
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 08:02 UTC, seilagamo commented on pkg/api/service/teams.go
> +	if s.vulcantrackerClient == nil {
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 08:03 UTC, seilagamo commented on pkg/api/service/teams.go
> +		return teams, nil
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 08:03 UTC, seilagamo commented on pkg/api/service/teams.go
> +		return team, nil
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 08:03 UTC, seilagamo commented on pkg/api/service/tickets.go
> +	if s.vulcantrackerClient == nil {
Fixed in commit 519b2dce7565f3dd38e8589ab0b487ccb51c4c8c

2023-06-27 10:22 UTC, manelmontilla approved these changes
LGTM

2023-06-28 14:22 UTC, merged