Malformed asset identifier makes outbox CDC to stop processing
adevinta/vulcan-api pull request #150
Opened 2023-05-09 10:55 UTC by seilagamo

A user can add an asset through the UI (and hence through the API) with a malformed identifier, for example, an AWS account ARN with a space in the middle:

`arn:aws:iam:: 012345678900:root`

This causes the outbox CDC to stop working as the subsequent request to the vulnerabilitydb-api to propagate the action fails:
```
component=CDC error=\"<html><body><h1>400 Bad request</h1>\\nYour browser sent an invalid request.\\n</body></html>\\n\" id=93995f78-025e-413e-99d4-d047a4198bd7 action=DeleteAsset retries=20\n","stream":"stderr","time":"2023-05-03T09:05:32.744982511Z"
```

This PR adds two types of controls:
- The first one is a check to avoid creating assets with malformed identifiers
- The second one is to query escape the strings when we make requests to vulcandb.

2023-05-09 14:41 UTC, julianvilas requested changes
The PR looks very good to me! Just a minor suggestion pointed.

2023-05-09 14:41 UTC, julianvilas commented on pkg/api/asset.go
> +	arnRegex := regexp.MustCompile(`^arn:(aws|aws-cn|aws-us-gov):([a-z0-9-]+):([a-z\d-]*):([0-9]*):([a-zA-Z0-9_-]*)(//?[a-zA-Z0-9_-]+)*(//.*)?.*$`)
As a general rule I'd avoid using `Must*` like functions except on command-line tools, because errors in the function cause `panic`. I'd suggest rather using [regexp.Compile](https://pkg.go.dev/regexp#Compile) and perform the error handling (i.e. `err != nil` => `return false`).

2023-05-10 06:00 UTC, seilagamo commented on pkg/api/asset.go
> +	arnRegex := regexp.MustCompile(`^arn:(aws|aws-cn|aws-us-gov):([a-z0-9-]+):([a-z\d-]*):([0-9]*):([a-zA-Z0-9_-]*)(//?[a-zA-Z0-9_-]+)*(//.*)?.*$`)
Thanks for the tip!

2023-05-10 06:52 UTC, seilagamo commented on pkg/api/asset.go
> +	arnRegex := regexp.MustCompile(`^arn:(aws|aws-cn|aws-us-gov):([a-z0-9-]+):([a-z\d-]*):([0-9]*):([a-zA-Z0-9_-]*)(//?[a-zA-Z0-9_-]+)*(//.*)?.*$`)
Fixed in commit c21e7c7c4323678112970d087f97c958298d8ef0

2023-05-10 08:26 UTC, julianvilas approved these changes
Great job!

2023-05-10 08:34 UTC, merged