Present exposure stats through the Vulcan API
adevinta/vulcan-api pull request #20
Opened 2021-06-04 09:50 UTC by gguillemas

This PR allows users to access the endpoints [incorporated in the Vulnerability DB API](https://github.com/adevinta/vulnerability-db-api/pull/17) through the Vulcan API. The endpoints have been exposed both for specific teams and globally almost identically as with the MTTR stats endpoints. The changes have been tested with the linked PR and work as expected.

2021-06-07 23:52 UTC, filewalkwithme commented on pkg/vulnerabilitydb/vulnerabilitydb_test.go
> +		server.Close()
Can we move the `Close()` method to a `defer` instruction placed just after the server instantiation?

2021-06-08 00:00 UTC, filewalkwithme commented on cmd/vulcan-api-cli/design/stats.go
> +var StatsAveragesMedia = MediaType("statsAverages", func() {
This `statsAverages` seems to be unused, is that correct?

2021-06-08 00:01 UTC, filewalkwithme requested changes
Hi @gguillemas, I have added just 2 minor comments. Let me know if you have any questions.

2021-06-08 13:51 UTC, gguillemas commented on cmd/vulcan-api-cli/design/stats.go
> +var StatsAveragesMedia = MediaType("statsAverages", func() {
You are correct, I forgot to replace the media type used on the endpoint. Fixed in d7d856f.

2021-06-08 13:54 UTC, gguillemas commented on pkg/vulnerabilitydb/vulnerabilitydb_test.go
> +		server.Close()
As we discussed directly, this line is copied from the other tests and should be addressed for all in a separate PR.

2021-06-09 10:15 UTC, filewalkwithme approved these changes
LGTM

2021-06-09 10:15 UTC, merged

2021-06-09 10:15 UTC, filewalkwithme commented on pkg/vulnerabilitydb/vulnerabilitydb_test.go
> +		server.Close()
Agree!