WIP
adevinta/vulcan-api pull request #205
Opened 2023-07-19 15:10 UTC by manelmontilla

2023-10-10 15:26 UTC, jesusfcr requested changes
Very impressive!
Added a couple of comments.

2023-10-16 14:05 UTC, manelmontilla commented on contrib/dev/local-dev.toml
>  api_base_url = "http://localhost:8084"
Good catch thank you, removing them.

2023-10-16 14:07 UTC, manelmontilla commented on pkg/api/endpoint/reports.go
> -func makeFindReportEndpoint(s api.VulcanitoService, logger kitlog.Logger) endpoint.Endpoint {
Absolutely good catch, thank you.

2023-10-18 10:25 UTC, jesusfcr approved these changes
LGTM

2023-10-23 09:30 UTC, merged