Add endpoints for asset annotations
adevinta/vulcan-api pull request #22
Opened 2021-06-12 07:33 UTC by svalentino

Draft PR for introducing asset annotations.

Pending items:
- extend `/teams/<id>/assets` and `/teams/<id>/assets/multistatus` endpoints to handle asset annotations during asset creation
- extend `/teams/<id>/assets` to allow querying by `identifier`

2021-06-25 10:28 UTC, julianvilas approved these changes
LGTM

2021-06-25 18:12 UTC, filewalkwithme requested changes
Hi @svalentino , I have finished the review. Please, let me know if you have any questions.

2021-06-25 18:12 UTC, filewalkwithme commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +	Action("list", func() {
oh, actually I am wrong. Feel free to dismiss this comment.

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/endpoint/asset_annotations.go
> +		return Ok{response}, nil
For the sake of consistency, I would change the DELETE operation to return a 204 NO Content

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/endpoint/assets.go
> +	AssetAnnotations map[string]string `json:"annotations"`
Stylish change: Can we name this field simply as `Annotations`?

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/store/assets.go
> +		Preload("AssetAnnotations").
Why preload `AssetAnnotations` here?

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/store/assets.go
> +		Preload("AssetAnnotations").
Same, why Preload AssetAnnotations here?

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/store/assets_test.go
> +	ignoreFieldsAsset   = cmpopts.IgnoreFields(api.Asset{}, append(baseModelFieldNames, "Team", "AssetType", "AssetTypeID", "ClassifiedAt", "AssetAnnotations")...)
we are ignoring `"Team", "AssetType", "AssetTypeID` here because we dont control the generated `ID's` for these entities during test execution. For other entities, like `groups`, we have better control. Can we include `AssetAnnotations` among the fields to be compared during tests?

2021-06-25 18:12 UTC, filewalkwithme commented on pkg/api/transport/routes.go
> +	r.Methods("PATCH").Path("/api/v1/teams/{team_id}/assets/{asset_id}/annotations").Handler(newServer(e[endpoint.UpdateAssetAnnotations], endpoint.AssetAnnotationRequest{}, logger, endpoint.UpdateAsset
I would include also a PUT operation, to replace the entire collection of annotations in a single operation

2021-06-25 18:12 UTC, filewalkwithme commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +	Attributes(func() {
Now I understood that this is a limitation of GOA, right? We cant have a `HashOf(string, string)` as a top level response. Maybe we need to refactor the application to comply with GOA. I dont like it, but I cant see other options here, sadly.

2021-06-28 13:03 UTC, svalentino commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +	Attributes(func() {
This has been refactored in c20ee98

2021-06-28 13:05 UTC, svalentino commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +	Action("list", func() {
Well, based on our discussion, even though those parameters are implicitly inherited from the "parent" endpoint, it make sense to explicitly declare them. Done in 5c06bd6

2021-06-28 13:05 UTC, svalentino commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +		Response(OK, AssetAnnotationsResponseExample)
Agree. Adjusted in 3c095b0.

2021-06-28 13:05 UTC, svalentino commented on pkg/api/asset.go
> +		for _, an := range a.AssetAnnotations {
Good point - cannot agree more. Refactored in c20ee98

2021-06-28 13:06 UTC, svalentino commented on pkg/api/endpoint/asset_annotations.go
> +		return Ok{response}, nil
Done in 3c095b0

2021-06-28 13:07 UTC, svalentino commented on pkg/api/endpoint/assets.go
> +	AssetAnnotations map[string]string `json:"annotations"`
Done as part of c20ee98

2021-06-28 13:07 UTC, svalentino commented on pkg/api/store/assets.go
> +		Preload("AssetAnnotations").
You right. Preload removed in a014f6d

2021-06-28 13:07 UTC, svalentino commented on pkg/api/store/assets.go
> +		Preload("AssetAnnotations").
You right. Preload removed in a014f6d

2021-06-28 13:08 UTC, svalentino commented on pkg/api/store/assets_test.go
> +	ignoreFieldsAsset   = cmpopts.IgnoreFields(api.Asset{}, append(baseModelFieldNames, "Team", "AssetType", "AssetTypeID", "ClassifiedAt", "AssetAnnotations")...)
Fair point here as well. I've adjusted the test units to **not** ignore the `AssetAnnotations` property in d06d60d

2021-06-28 13:09 UTC, svalentino commented on pkg/api/transport/routes.go
> +	r.Methods("PATCH").Path("/api/v1/teams/{team_id}/assets/{asset_id}/annotations").Handler(newServer(e[endpoint.UpdateAssetAnnotations], endpoint.AssetAnnotationRequest{}, logger, endpoint.UpdateAsset
Hard to argue with that! :) Implemented in f7fe6ce

2021-06-29 15:53 UTC, filewalkwithme commented on pkg/api/asset.go
> +		for _, an := range a.AssetAnnotations {
Thank you!

2021-06-29 15:54 UTC, filewalkwithme commented on pkg/api/endpoint/assets.go
> +	AssetAnnotations map[string]string `json:"annotations"`
Thanks!

2021-06-29 15:54 UTC, filewalkwithme commented on pkg/api/store/assets.go
> +		Preload("AssetAnnotations").
Perfect!

2021-06-29 15:54 UTC, filewalkwithme commented on pkg/api/transport/routes.go
> +	r.Methods("PATCH").Path("/api/v1/teams/{team_id}/assets/{asset_id}/annotations").Handler(newServer(e[endpoint.UpdateAssetAnnotations], endpoint.AssetAnnotationRequest{}, logger, endpoint.UpdateAsset
Thanks @svalentino !

2021-06-29 16:15 UTC, filewalkwithme commented on cmd/vulcan-api-cli/design/asset_annotations.go
> +	Attributes(func() {
Uff, thanks for taking care of this!

2021-06-29 16:16 UTC, filewalkwithme approved these changes
LGTM!

thanks a lot for this change!

2021-07-05 10:14 UTC, merged