Hostname check with DNS or not
adevinta/vulcan-api pull request #276
Opened 2023-12-06 09:41 UTC by alexanderkjall

add an environment variable to control if the hostname check should be performed with a dns resolution or not.

https://github.com/adevinta/vulcan-types/pull/142 needs to be merged and released before this can be evaluated I guess :)

2023-12-12 11:56 UTC, manelmontilla requested changes

2023-12-12 11:56 UTC, manelmontilla commented on pkg/api/asset.go
> +		if os.Getenv("VULCAN_HOSTNAME_VALIDATION_WITH_DNS") == "false" {
We don't directly access env vars in the logic of the program.
In order to add a config option you need to:
1. Add it to the config file that maps env vars to parameters in the [config file](https://github.com/adevinta/vulcan-api/blob/master/config.toml)
I think there isn't any section that makes sense to add this new param, so I would add a new section, something like this:
```toml
[assets]
dns_hostname_validaton = "$DNS_HOSTNAME_VALIDATION"
``` 
2. Map the value in the [run script of the container](https://github.com/adevinta/vulcan-api/blob/master/run.sh) by adding something like this:

```bash
export DNS_HOSTNAME_VALIDATION=${DNS_HOSTNAME_VALIDATION:-true}
```
3. Add the new section in the struct representing the [configuration of the api](https://github.com/adevinta/vulcan-api/blob/master/cmd/vulcan-api/commands.go#L149)

2023-12-18 14:49 UTC, alexanderkjall commented on pkg/api/asset.go
> +		if os.Getenv("VULCAN_HOSTNAME_VALIDATION_WITH_DNS") == "false" {
Thanks for the review, I updated the branch and tried to apply this feedback.

2024-01-08 16:09 UTC, manelmontilla requested changes

2024-01-09 15:29 UTC, alexanderkjall commented on cmd/vulcan-api/commands.go
> +	DnsHostnameValidation string `mapstructure:"dns_hostname_validation"`
thanks for the link, fixed :)

2024-01-09 15:30 UTC, alexanderkjall commented on pkg/api/endpoint/assets.go
> +func makeCreateAssetEndpoint(s api.VulcanitoService, logger kitlog.Logger, dnsHostnameValidation bool) endpoint.Endpoint {
Good suggestion, this should be fixed now.

2024-01-29 09:16 UTC, alexanderkjall commented
Any update on this one?

2024-02-12 07:34 UTC, alexanderkjall commented
Any update on this one?

2024-04-04 13:33 UTC, kozmic commented
Now that the https://github.com/adevinta/vulcan-types/pull/142 has been merged, could this PR be reviewed and merged @manelmontilla ?

2024-04-24 16:01 UTC, jesusfcr commented
Fixed and merged https://github.com/adevinta/vulcan-api/pull/317

2024-04-24 16:01 UTC, closed without merging