Allow configure tracker for all the teams
adevinta/vulcan-api pull request #339
Opened 2024-04-09 08:05 UTC by jesusfcr

2024-04-12 09:35 UTC, seilagamo requested changes

2024-04-12 09:40 UTC, jesusfcr commented on pkg/api/service/tickets_test.go
> +func TestVulcanitoService_OnboardeTeam(t *testing.T) {
thanks, fixed

2024-04-12 09:40 UTC, jesusfcr commented on pkg/api/service/tickets_test.go
> +Copyright 2021 Adevinta
thanks, fixed ;)

2024-04-12 09:41 UTC, seilagamo submitted a review, later dismissed
LGTM

2024-04-15 14:17 UTC, seilagamo approved these changes
LGTM

2024-04-18 13:49 UTC, merged