Add a new jobs endpoint to serve status information for async requests
adevinta/vulcan-api pull request #38
Opened 2021-12-13 11:06 UTC by julianvilas

This endpoint will be used to retrieve information about the status of async requests being processed in the background.

Modifications introduced:

* A new database table to store jobs, with these fields:
```| id | team_id | operation | status | created_at | updated_at |```
* A new global endpoint to retrieve a job by its ID:
```GET /api/v1/jobs/{job_id}/```

2021-12-14 08:26 UTC, ka3de requested changes
Hey @julianvilas good job! :+1: 
Overall everything looks very good but I think there are some minor things to take a look at and a discussion pending about the support for "global jobs" (see my comment on `pk/api/job.go`).

Additionally I believe we are missing the endpoint "entry" in he metrics middleware (`pkg/api/middleware/metrics.go`), for which I believe we'll have to add a new type of entity for `job`.

2021-12-14 08:26 UTC, ka3de commented on pkg/api/job.go
> +// the operation.
This comment made me think that this "non-global" operation is not going to be possible according to the table definition we made because we are using a foreign key on `teams(id)`. We should probably discuss and rethink about this, if this "global-operations" are gonna be a valid use case and how to handle that.

2021-12-14 08:26 UTC, ka3de commented on pkg/api/service/jobs.go
> +	}
No big deal, and we can keep it here, but do you think this validation would make more sense at the endpoint level?

2021-12-14 11:28 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +var _ = Resource("job", func() {
Totally agree. Will change it.

2021-12-14 17:00 UTC, julianvilas commented on pkg/api/store/job.go
> +		return nil, db.logError(errors.NotFound("Job does not exists"))
Done!

2021-12-14 17:06 UTC, julianvilas commented on pkg/api/service/jobs.go
> +	}
Yes, absolutely. I thought it was done but it wasn't.

2021-12-14 17:09 UTC, julianvilas commented on pkg/api/service/jobs.go
> +	}
Done

2021-12-15 10:25 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +		Description("Describe job")
Sure! I'm on it.

2021-12-15 11:50 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +var _ = Resource("job", func() {
Done!

2021-12-15 11:50 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +		Description("Describe job")
Done!

2021-12-16 08:25 UTC, ka3de reviewed
I @julianvilas great job! :+1: 
Thanks for addressing the previous comments, I think we have a better idea now of what we want to achieve.
I made some comments, mostly simple things except for the comments about using JSONB type for Job result field. We can discuss this and take a look together to see what is the best approach.

2021-12-16 08:25 UTC, ka3de commented on pkg/api/job.go
> +	Result string `gorm:"Column:result"`
Should we use the `JobResult` struct here to represent the `Result` field?
I have some doubts about how Gorm will treat this when inserting into DB when using a struct, so we can check and discuss.

2021-12-16 08:25 UTC, ka3de commented on pkg/api/job.go
> +		return errors.New("valid states are PENDING, RUN or DONE")
In reference to the comment above, should we use `RUN` or `RUNNING` as status?
Also, super silly but, I guess it's correct to use `state` and `status` interchangeably in English, but should we s/states/status here for coherence?

2021-12-16 08:25 UTC, ka3de commented on db/sql/V1.51__create_jobs_table.sql
> +    result TEXT,
Should we use `jsonb` type here? That will allow us to take advantage of PSQL capabilities to interact with JSON data. Also I guess Gorm will provide better support for our implementation in that way too.

2021-12-16 11:40 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +	- 'PENDING': The job has been noted an is pending to be processed
Done!

2021-12-16 11:40 UTC, julianvilas commented on cmd/vulcan-api-cli/design/jobs.go
> +	- 'DONE': The job has finished, either successfully os unsuccesfully. Result.error needs to be processed to determine it
Done!

2021-12-16 11:40 UTC, julianvilas commented on pkg/api/job.go
> +	Operation string `validate:required`
Done!

2021-12-16 11:40 UTC, julianvilas commented on pkg/api/job.go
> +	case "RUN":
Done!

2021-12-16 11:42 UTC, julianvilas commented on pkg/api/job.go
> +	case "DONE":
Let's discuss it together with the JSONB approach in the meeting we have and choose whatever fits better :)

2021-12-16 11:42 UTC, julianvilas commented on pkg/api/job.go
> +	Result string `gorm:"Column:result"`
Let's discuss it in the meeting we have and choose whatever fits better :)

2021-12-16 11:42 UTC, julianvilas commented on pkg/api/job.go
> +		return errors.New("valid states are PENDING, RUN or DONE")
Done!

2021-12-16 11:42 UTC, julianvilas commented on db/sql/V1.51__create_jobs_table.sql
> +    result TEXT,
Let's discuss it in the meeting we have and choose whatever fits better :)

2021-12-16 11:44 UTC, julianvilas commented
Thanks for your review and comments @ka3de :) 

I've addressed all your comments excepts those we plan to discuss in a meeting: the JSONB Results and the JobStatus topics. Thanks again!

2021-12-16 16:02 UTC, ka3de approved these changes
LGTM.

2021-12-16 16:44 UTC, merged

2021-12-16 16:45 UTC, julianvilas commented on pkg/api/job.go
> +	case "DONE":
We went for the constants option. In the future we might explore using enums both in Go code and in the database table.

2021-12-16 16:46 UTC, julianvilas commented on pkg/api/job.go
> +	Result string `gorm:"Column:result"`
We went for the JSONB approach finally.

2021-12-16 16:46 UTC, julianvilas commented on db/sql/V1.51__create_jobs_table.sql
> +    result TEXT,
We went for the JSONB approach finally.