Add authorization tests for issues
adevinta/vulcan-api pull request #399
Opened 2024-08-26 14:21 UTC by jesusfcr

2024-08-26 14:51 UTC, jroimartin approved these changes
LGTM. Just a couple of questions.

2024-08-26 14:51 UTC, jroimartin commented on postman/vulcan-authorization.postman_collection.json
> -								"id": "3eee6672-6106-4672-b4e2-42306a86c68d",
Just out of curiosity. Why are all the `id` fields gone?

2024-08-26 14:51 UTC, jroimartin commented on postman/vulcan-authorization.postman_collection.json
> +						},
I'm not familiar with Postman. But, is this required? Auth seems to be set on a higher level?

```suggestion
```

2024-08-26 14:53 UTC, jesusfcr commented on postman/vulcan-authorization.postman_collection.json
> -								"id": "3eee6672-6106-4672-b4e2-42306a86c68d",
Probably my desktop version of postman removed the ids on export.

2024-08-26 15:15 UTC, jroimartin requested changes
As discussed after seeing that the tests fail because of the proposed change. It would be good to test both:

- `401` is returned when the token is missing or not valid.
- `403` is returned when the token is not authorized.

2024-08-26 20:07 UTC, jroimartin approved these changes
LGTM

2024-08-27 07:00 UTC, jroimartin approved these changes

2024-08-27 07:01 UTC, merged