Add team filters and use team for authorization with Vulnerability DB
adevinta/vulcan-api pull request #61
Opened 2022-06-08 11:24 UTC by gguillemas

2022-07-04 11:01 UTC, manelmontilla commented
Apart from the comments in the modifications, I'm leaving here comments about modifications I think we need to do, but that I can not comment directly in the file because there are no modifications in the PR.

*  Here: https://github.com/adevinta/vulcan-api/blob/ed9365aa91d6931dbd735ff6d8666dd773f18eab/pkg/api/store/cdc/parser.go#L138

I think we should also pass the team id, so the VulnDB can associate the target with the team, so it would be something like this:
```go
payload := api.CreateTarget{
		Identifier: dto.Asset.Identifier,
		Tags:       []string{dto.Asset.Team.Tag},
		Teams: []string{dto.Asset.TeamID},
	}
```

2022-07-04 13:05 UTC, manelmontilla requested changes

2022-07-05 14:57 UTC, gguillemas commented on pkg/api/store/cdc/parser.go
> +	err = p.VulnDBClient.DeleteTeamTag(context.Background(), dto.Team.ID, dto.Team.Tag, dto.Team.Tag)
Good catch! I added this call on [094d6b0](https://github.com/adevinta/vulcan-api/pull/61/commits/094d6b0996c10bad6e067c7bfc78626e47271a6d).

2022-07-05 14:57 UTC, gguillemas commented on pkg/api/store/cdc/parser.go
> +	err = p.VulnDBClient.DeleteTeamTag(context.Background(), dto.Team.ID, dto.Team.Tag, dto.Team.Tag)
You are correct, I have fixed this on [094d6b0](https://github.com/adevinta/vulcan-api/pull/61/commits/094d6b0996c10bad6e067c7bfc78626e47271a6d).

2022-07-06 08:42 UTC, manelmontilla approved these changes
LGTM

2022-07-26 14:09 UTC, ka3de submitted a review, later dismissed
LGTM.

2022-08-11 10:21 UTC, ka3de commented on pkg/api/store/team.go
> +			return nil, db.logError(errors.NotFound(res.Error))
Should this be an error? Or just return a void list of teams?

2022-08-11 10:21 UTC, ka3de commented on pkg/api/transport/request_decoder.go
> +			// This should not happen never, but still...
s/not happen never/never happen ?

2022-08-11 10:21 UTC, ka3de commented on pkg/api/transport/request_decoder.go
> +			// This should not happen never, but still...
s/not happen never/never happen ?

2022-08-11 10:21 UTC, ka3de commented on pkg/api/transport/request_decoder.go
> +			// This should not happen never, but still...
s/not happen never/never happen ?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
Should we put a comment above this line in order to explain why are we performing this "translation"?

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +func tagsToTeams(ctx context.Context, s api.VulcanitoService, tagsStr string) (string, error) {
Should we put a small comment here that explains more or less this function? Even though it's not exported I think this is a tricky behavior to understand.

2022-08-11 10:22 UTC, ka3de commented on pkg/api/endpoint/stats.go
> +	teams, err := s.FindTeamsByTags(ctx, tags)
I have mix reviews about performing the translation here in the "endpoints" layer instead of at the service layer. The good points that I see is that doing it here we can get rid of the "tag" related parameters in the param structs that will be forwarded to the service layer. Was that the reason you decided to do it here? What were the pros and cons that went into your decision to implement it here? Just to understand it better.

2022-08-11 10:45 UTC, manelmontilla commented on pkg/api/store/team.go
> +			return nil, db.logError(errors.NotFound(res.Error))
That's a good question, I make to work like the method: `FindTeamByTag`  but it is true that in this case that does not make sense, furthermore the query won't never return a not found error. (It's even tested in the ``teams_test.go`` file)

2022-08-11 10:52 UTC, manelmontilla commented on pkg/api/store/team.go
> +			return nil, db.logError(errors.NotFound(res.Error))
Yes that's what's happening indeed because the query won't return a not found error in any cae (its indeed probed in the ``team_test.go``), I'm removing the ``if``

2022-08-11 10:54 UTC, manelmontilla commented on pkg/api/transport/request_decoder.go
> +			// This should not happen never, but still...
Yes thanks!!

2022-08-11 10:58 UTC, manelmontilla commented on pkg/api/endpoint/stats.go
> +			teams, err := tagsToTeams(ctx, s, r.Tags)
It could add  some context so yes.

2022-08-11 11:06 UTC, manelmontilla commented on pkg/api/endpoint/stats.go
> +func tagsToTeams(ctx context.Context, s api.VulcanitoService, tagsStr string) (string, error) {
Ok, I considered commenting it but TBH I though it was not necessary, in any case if you it wasn't obvious when you were doing the review then it's Cleary needed.

2022-08-11 11:33 UTC, manelmontilla commented on pkg/api/endpoint/stats.go
> +	teams, err := s.FindTeamsByTags(ctx, tags)
Well I think that right now, after looking at the code of other endpoints, we are already not only using the endpoints to map directly requests to structs and call the service layer. We are already using them, in some cases to do some translations.
For instance in this file in the [previous version](https://github.com/adevinta/vulcan-api/blob/8fbad1370dc205896193d512bb903eb4c95ff881/pkg/api/endpoint/stats.go#L45), or in [this other endpoint](https://github.com/adevinta/vulcan-api/blob/8fbad1370dc205896193d512bb903eb4c95ff881/pkg/api/endpoint/reports.go#L30) we are something similar but for the other way around, that is translating a team id to a tag.

2022-08-11 12:00 UTC, ka3de submitted a review, later dismissed
LGTM.

2022-08-11 14:00 UTC, gguillemas commented on pkg/api/endpoint/stats.go
> +				return nil, errors.NotFound("There are no teams with specified tags")
I would change "no teams with specified tags" to "no teams with **the** specified tags". Otherwise the message could be understood as that there are no teams with tags specified in the Vulcan API at all.

2022-08-12 06:35 UTC, manelmontilla commented on pkg/api/endpoint/stats.go
> +				return nil, errors.NotFound("There are no teams with specified tags")
Makes sense thanks.

2022-08-12 06:37 UTC, manelmontilla commented on pkg/api/endpoint/stats.go
> +	IDs := []string{}
👍

2022-08-17 09:30 UTC, danfaizer approved these changes
LGTM

2022-08-17 10:37 UTC, danfaizer approved these changes
I approve this but we will must, eventually, generate a proper version of the vulnerabilitydb-api dependency and pin the proper version in here.

2022-08-17 10:41 UTC, merged