Asset bumper
adevinta/vulcan-api pull request #65
Opened 2022-07-11 16:10 UTC by manelmontilla

This PR adds a set of new features needed for the Vulcan API to start implementing and Async API that publishes in a Kafka event stream all the CRUD operations of the Assets in the Vulcan API. 
* It adds a new command line tool that can be used to bootstrap a Kafka topic with the initial values of the Assets in vulcan. Notice that when executed the tool will lock the tables: ``Teams`` and  ``Assets`` for writing, so it should be used carefully.
* It also adds the specification of the Asynchronous API that Vulcan will expose, even though the API is not yet implementented.
* Adds the tooling needed to generate the models from the Async API specification, and the first version of these autogenerated models.

2022-07-12 11:18 UTC, gguillemas requested changes
I have added some comments, most of them small nitpicks. The rest looks good!

2022-07-12 11:18 UTC, gguillemas commented on pkg/api/store/gorm.go
> +		stm := fmt.Sprintf("LOCK TABLE ONLY %s IN EXCLUSIVE MODE", t)
I understand we cannot use prepared statements here and that this function will not accept user input by design, but just to be sure I would remove all characters that are not `[a-zA-Z0-9_-]` (or whatever we see fit) from the table names to reduce the risk of SQL injection in the future.

2022-07-12 11:18 UTC, gguillemas commented on pkg/asyncapi/gen/gen.sh
> +# GENDIR="$(realpath pkg/asyncapi/gen)"
Can these comments be removed?

2022-07-12 13:18 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +		assets, err := r.Read()
yes!!
it is actually checked in the exit condition on the loop just above!!
```go
for err == nil {
``` 
It is true that this pattern is not very common in go, but it this case as for instance in the case of a Reader, the algorithm it's basically:  read until you got an error, if the error is ``EOF``  everything was okey and you've done, if the error is not ``EOF`` something when wrong while trying to read, so stop reading and return and error.

2022-07-12 13:39 UTC, gguillemas commented on cmd/vulcan-asset-bumper/main.go
> +		assets, err := r.Read()
I see! I was worried than we would have `err != nil` and also `len(assets) != 0` leading to some strange behavior inside the `for` loop. Now I see that this is precisely the point that we are looking to deal with when `err == ErrReadAssetsFinished`.

2022-07-12 15:35 UTC, manelmontilla commented on pkg/api/store/gorm.go
> +		stm := fmt.Sprintf("LOCK TABLE ONLY %s IN EXCLUSIVE MODE", t)
Yeah makes sense, thank you.

2022-07-12 15:36 UTC, manelmontilla commented on pkg/asyncapi/gen/gen.sh
> +# GENDIR="$(realpath pkg/asyncapi/gen)"
Yes absolutely, they are leftovers

2022-07-13 07:34 UTC, gguillemas submitted a review, later dismissed
LGTM

2022-07-14 22:04 UTC, jroimartin requested changes

2022-07-14 22:04 UTC, jroimartin commented on pkg/asyncapi/vulcan.go
> +	DebugF(string, ...any)
I would rename them to `Errorf`, `Infof` and `Debugf`, so they follow the convention used by `fmt` and `log`.

2022-07-15 07:46 UTC, jroimartin commented
Also, I think the PR is missing some tests. At least for `cmd/vulcan-asset-bumper/main.go` and `pkg/asyncapi/kafka/client.go`.

2022-07-15 08:26 UTC, manelmontilla commented
After the reviews it's pretty clear this PR is not ready to be merged, for instance the function ``bump`` is completely FUBA. It looks I made modifications before creating the PR and screwed it all (I must be brain dead when i did this). Also the root cause of this is that I didn't make tests for the critical functions, which is unacceptable. So I'm converting this PR to a draft,  make tests and review everything again. Thank you very much for all the catches of the CRs.

2022-08-09 10:01 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	if err == store.ErrReadAssetsFinished {
Regarding the errors.Is, no I think it's better to use an exact comparison here, we don't want the condition to be true if err can unwrap to an ``store.ErrReadAssetsFinished`` we want it to be true only if the err is exactly ``store.ErrReadAssetsFinished``. Regarding the ``r.Read`` yes this loop is completely broken I'm rewriting it.

2022-08-24 14:45 UTC, manelmontilla commented on README.md
> +pkg/asyncapi/gen/gen.sh docs/async/asyncapi.yaml asyncapi > pkg/asyncapi/models.go
Yes makes sense.

2022-08-24 14:45 UTC, manelmontilla commented on README.md
> +* [Asynchronous API](docs/async/asyncapi.yml)
👍

2022-08-24 14:46 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +won't be able to work meanwhile this tool is running.`
Yes I tried to make that point more clear.

2022-08-24 14:47 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +		fmt.Fprintf(os.Stderr, "error reading config %s:%+v", *configFile, err)
No, just because I'm used to it.

2022-08-24 14:48 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	cfg := &config{}
Yes it was a mistake (passing the pointer to a pointer)

2022-08-24 14:49 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	for err == nil {
Yes absolutely fixed this together with other bugs.

2022-08-24 14:50 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	}
Yes I think it's a good improvement.

2022-08-24 14:53 UTC, manelmontilla commented on docs/async/asyncapi.yaml
> +        - GitRepository
Yes makes sense.

2022-08-24 14:59 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	goerrors "errors"
Yes that's true, but in this case I think it's better the leave it as it is, indeed I though the same when I was coding it, but as in the rest of the files of this project ``errors`` is used to refer to the Adevinta errors I prefer to do the same thing here.

2022-08-24 15:01 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +		assets, err := r.Read()
Yes, well something similar I coded that loop fixing this and other problems.

2022-08-24 15:03 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	limit := a.pageSize + 1
I try to get one more asset of the page size just to be able to determine if there are one more page of assets.

2022-08-24 15:46 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	if len(assets) == limit {
Well as I understand it, yes it is always true. Take into account that I'm always trying to read page_size + 1 assets. That means that at most we are going to get a number less or equal to limit. If it is less that the limit we have no more assets to return, if we it is equal to the limit, as the limit is page_size + 1, as we will return limit - 1 assets (the page size) its always true that there will be at least one more asset to return (the one that we didn't return to the user). 
 I added a test called ``ReturnsAssetsWhenLimitMultNOfAssets`` for make it cleaner.
I also removed the field ``total``  from the ``AssetReader`` as it was not useful in the general case, when the tables are not blocked, and I think was causing confusion reading the code.

2022-08-24 15:50 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	//res := tx.Raw(stm, limit).Scan(&assets)
Yes removed.

2022-08-24 15:51 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	if len(assets) == limit {
Look at my answer in the question about this above.

2022-08-29 14:14 UTC, jroimartin requested changes

2022-08-29 15:15 UTC, jroimartin commented on cmd/vulcan-asset-bumper/main.go
> +		assets, err = r.Read()
Another approach: https://pkg.go.dev/bufio#example-Scanner-Lines

2022-08-29 16:04 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	}
Yes it's better.

2022-08-29 16:04 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	}
Yes changed thanks

2022-08-29 16:15 UTC, manelmontilla commented on pkg/asyncapi/_gen/gen.sh
> +cd "$(dirname $0)/../../.."
👍

2022-08-29 16:20 UTC, manelmontilla commented on README.md
> +The structures representing the data models of the async API in go are
Yeah I get what you mean, but IDK why but writing ``Go``  does look right to me 😄  so I will leave it as is.

2022-08-29 16:23 UTC, manelmontilla commented on README.md
> +automatically generated. To update the models run this command in the root of
I think both are correct.

2022-08-29 16:25 UTC, manelmontilla commented on _script/docker-compose-kafka.yaml
> +        image: confluentinc/cp-zookeeper:latest
👍

2022-08-29 16:39 UTC, manelmontilla commented on _script/docker-compose-kafka.yaml
> +        - zookeeper
I think in this case is not needed,  I basically copied the definition from [here](https://github.com/confluentinc/cp-all-in-one/blob/851036bd3e377d3ef007ab115b7fee4aa9f281ab/cp-all-in-one-community/docker-compose.yml) which I consider more or less the "official" version, I think Kafka retries by itself for quite a while if Zookeeper is not up.

2022-08-30 08:22 UTC, manelmontilla commented on _script/start-kafka
> +SOURCE_DIR="$(dirname $(realpath "$0"))"
True!!

2022-08-30 08:27 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	configFile := flag.String("c", "", "path the config file")
👍

2022-08-30 08:50 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	if *configFile == "" {
Yes well,  I decided to use a flag here because the other binaries in the repo (for instance vulcan-api) use the flag "c" to specify the configuration file path, but it is true that in those cases the argument is not mandatory (because if not present it defaults to a well known config file name in the user's home)

2022-08-30 09:09 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	if *configFile == "" {
So what I'm doing is to set a default path for the config file posting to the user's home directory just to keep consistent with the rest of the binaries of the repo.

2022-08-30 09:18 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	fmt.Fprintln(os.Stderr, description)
You're are right that was removed when changed the wrapping of the original  ``usage function`` I'm reverting it.

2022-08-30 09:28 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +func parseLogLevel(l string) level.Option {
Yes that will improve the tool.

2022-08-30 09:44 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +	if err != nil {
ok I'll change it, I don't have a strong opinion here, I think it's matter of taste.

2022-08-30 09:45 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +func bump(v asyncapi.Vulcan, s store.Store, psize uint, logger levelLogger) error {
Yeah okey makes sense.

2022-08-30 10:12 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +			logger.Infof("sending batch of assets from %d to %d", from, to)
It's 1 indexed and inclusive, in any case, when the message is actually shown it contains the indexes (that is the user will see it starts from 1) so by now I think is good enough.

2022-08-30 10:14 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +			err = v.PushAsset(payload)
Yes good catch thank you, I'm changing the whole interface of the reader so this bug should be also fixed when using the new interface.

2022-08-30 10:15 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +
👍

2022-08-30 15:30 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main.go
> +		assets, err = r.Read()
I like the approach of the scanner so I'm implementing it.

2022-08-30 15:56 UTC, manelmontilla commented on cmd/vulcan-asset-bumper/main_test.go
> +LOOP:
TBH I think there is no clear convention for labels, it is true that in the spec they use camel case in the examples, but it's also true that in the [effective go](https://go.dev/doc/effective_go#names) there are no explicit statements about the names of the labels. In any case as it looks more common used I'm changing it.

2022-08-31 07:00 UTC, manelmontilla commented on db/README.md
> +# Setup local persistence components
I think in think using those synonyms is okey in this case so I'm leaving them.

2022-08-31 07:01 UTC, manelmontilla commented on db/docker-compose.yml
> +        image: confluentinc/cp-zookeeper:latest
okey I think that makes sense.

2022-08-31 07:07 UTC, manelmontilla commented on db/docker-compose.yml
> +        - zookeeper
I think Kafka retries automatically until the Zookeeper is up, also,  I'm basically copying the definition from the examples provided by Confluentic and also I've never seen any problems in running so by now, I'm leaving as it is.

2022-08-31 07:18 UTC, manelmontilla commented on db/persistence-start.sh
> +docker-compose up -d --remove-orphans
Yeah I agree that it could make sense, but this script is exactly the same script that was previously named [postgres-start.sh](https://github.com/adevinta/vulcan-api/blob/master/db/postgres-start.sh) I only renamed  it. So event though it could be improved, I think it's better to leave that possible improvements for other PR, also because it would imply modifying the rest of the scripts in this directory.

2022-08-31 07:26 UTC, manelmontilla commented on docs/asyncapi.yaml
> +        of time in Vulcan.
I think ``point of time`` is also valid, for instance is used [here](https://grammar.collinsdictionary.com/easy-learning/what-are-prepositions-of-time-in-english)

2022-08-31 08:26 UTC, manelmontilla commented on go.sum
> +github.com/google/go-cmp v0.5.8/go.mod h1:17dUlkBOakJ0+DkrSSNjCkIjxS6bF9zb3elmeNGIjoY=
Yes I dit, but I guess the question is when, I'll do it again.

2022-08-31 08:29 UTC, manelmontilla commented on pkg/asyncapi/_gen/package.json
> +    "license": "ISC",
I'm removing completely the license from here.

2022-08-31 08:39 UTC, manelmontilla commented on db/docker-compose.yml
> +        image: confluentinc/cp-kafka:latest
👍

2022-08-31 08:43 UTC, manelmontilla commented on pkg/asyncapi/_gen/gen.sh
> +    node gen.js ${SOURCE_FILE} ${GO_PACKAGE_NAME}"
👍

2022-08-31 08:44 UTC, manelmontilla commented on pkg/asyncapi/kafka/client.go
> +// Client implements an [EventStreamClient] using Kafka as the event stream
yeah good catch.

2022-08-31 08:50 UTC, manelmontilla commented on pkg/asyncapi/kafka/client.go
> +// is connected to. The method waits until kafka confirm the message has been
👍

2022-08-31 09:02 UTC, manelmontilla commented on pkg/asyncapi/kafka/client.go
> +	defer close(delivered)
AFAIK it is, but closing the channel is always done in all the examples in the Confluentic documentation and git repo, like [this one]( https://docs.confluent.io/kafka-clients/go/current/overview.html#synchronous-writes ), so I prefer to do it, just it case there is any subtle side effect I don't know that could make the client not work properly.

2022-08-31 09:06 UTC, manelmontilla commented on pkg/asyncapi/vulcan.go
> +//go:generate sh -c "_gen/gen.sh docs/asyncapi.yaml asyncapi > models.go && go fmt models.go"
Yeah true, it's a leftover, so even though it works, I'm removing it.

2022-08-31 09:11 UTC, manelmontilla commented on pkg/asyncapi/vulcan.go
> +// PushAsset publishes the state of an asset in the current point of time
"point of time" it's also valid, it's a synonym, for instance is used [here](https://grammar.collinsdictionary.com/easy-learning/what-are-prepositions-of-time-in-english)

2022-08-31 09:14 UTC, manelmontilla commented on pkg/testutil/testutils.go
> +// specified depth.For instance if a function named FuncA calls function,
👍

2022-09-01 10:50 UTC, jroimartin requested changes

2022-09-01 10:50 UTC, jroimartin commented on README.md
> +* [Asynchronous API](docs/asyncapi.yml)
s/yml/yaml/

2022-09-01 10:50 UTC, jroimartin commented on README.md
> +automatically generated. To update the models run this command from root of
s/from/from the/

2022-09-01 10:50 UTC, jroimartin commented on cmd/vulcan-asset-bumper/main.go
> +	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
This usage message does not seem to describe the CLI command line interface. As a user, I would expect something like:

```
usage: vulcan-asset-bumper [flags]
```

So it is clear what's the position of the flags, if there are positional arguments or no, etc.

2022-09-01 10:50 UTC, jroimartin commented on cmd/vulcan-asset-bumper/main.go
>  func (a levelLogger) Infof(s string, params ...any) {
s/a/l/

So it is consistent with `Errorf`.

2022-09-01 10:50 UTC, jroimartin commented on cmd/vulcan-asset-bumper/main.go
>  func (a levelLogger) Debugf(s string, params ...any) {
s/a/l/

So it is consistent with `Errorf`.

2022-09-01 10:50 UTC, jroimartin commented on pkg/api/store/assets_reader_test.go
> +				_ = reader.Read()
s/_ = // ?

In the other tests you just call `reader.Read()` without assigning it to `_`.

2022-09-01 10:50 UTC, jroimartin commented on pkg/api/store/assets_reader.go
> +	return a.tx.Commit().Error
Shouldn't you return `a.err` here?

2022-09-01 11:05 UTC, manelmontilla commented on pkg/api/store/assets_reader.go
> +	return a.tx.Commit().Error
Yes absolutely it is true that the original error is not lost (gets wrapped) but it is true is not correct.

2022-09-01 11:10 UTC, manelmontilla commented on README.md
> +* [Asynchronous API](docs/asyncapi.yml)
👍

2022-09-01 11:11 UTC, manelmontilla commented on README.md
> +automatically generated. To update the models run this command from root of
👍

2022-09-01 13:09 UTC, jroimartin approved these changes
LGTM

2022-09-01 13:16 UTC, jroimartin submitted a review, later dismissed

2022-09-01 14:09 UTC, jroimartin approved these changes

2022-09-01 14:30 UTC, merged