As an API user, I can change the status of a Finding
adevinta/vulcan-api pull request #8
Opened 2021-04-08 10:19 UTC by filewalkwithme

This PR introduces two new endpoints in the Vulcan API, allowing the user to submit Finding overrides.
A finding override is an event that changes attributes of a finding.
For the time being, the user will be allowed to change the `STATUS` field only.

```
LIST OF NEW ENDPOINTS

# Submit a Finding override event
POST /api/v1/teams/{team_id}/findings/{finding_id}/override

# Get a list of Finding override events
GET  /api/v1/teams/{team_id}/findings/{finding_id}/override
```

2021-04-12 13:01 UTC, ka3de requested changes
Hey @filewalkwithme , thanks for working on this!

Overall I found it pretty clear, just some considerations.
Also, I think the metrics middleware actions and entities mapping is missing for the new endpoints.
And, this might be a pain but..., as a general consideration for the PR, should we use the word `override` or `overwrite` ? [ref](https://www.grammar.com/override_vs_overwrite).

Another question that I have is, what are the plans for this new `override` endpoint and DB table? The plan is to extend it also to store other "status" changes for the findings like "snooze" ?

2021-04-14 15:35 UTC, filewalkwithme commented on pkg/api/service/finding.go
> +	}
Done!

2021-04-14 16:13 UTC, filewalkwithme commented on pkg/api/transport/routes.go
> +	r.Methods("POST").Path("/api/v1/teams/{team_id}/findings/{finding_id}/override").Handler(newServer(e[endpoint.CreateFindingOverride], endpoint.FindingOverrideRequest{}, logger, endpoint.CreateFindin
Done!

2021-04-14 16:16 UTC, filewalkwithme commented on pkg/api/store/cdc/parser.go
> +			processFunc = p.findingOverride
Done!

2021-04-14 16:19 UTC, filewalkwithme commented on pkg/api/endpoint/findings.go
> +		return Forbidden{nil}, nil
Done!

2021-04-14 16:30 UTC, filewalkwithme commented on db/sql/V1.49__create_findings_overrides.sql
> +    finding_id      UUID NOT NULL,
I have added the index.

2021-04-14 16:38 UTC, filewalkwithme commented
@ka3de 

> Also, I think the metrics middleware actions and entities mapping is missing for the new endpoints.

I have mapped the new FindingOverwrite endpoints to the existing `entityFinding` entity. Let me know if think that makes more sense to create a specific entity for the `FindingOverwrite`.

> And, this might be a pain but..., as a general consideration for the PR, should we use the word `override` or `overwrite` ? [ref](https://www.grammar.com/override_vs_overwrite).

Not strong opinion on this. I just modified to PR to use the term `overwrite` as you asked.

> Another question that I have is, what are the plans for this new `override` endpoint and DB table? The plan is to extend it also to store other "status" changes for the findings like "snooze" ?

I do believe that the "snooze" feature will be implemented using some sort of `tagging` system in the Vulnerability DB. Of course, we will be required to log this action in somewhere and for the moment we have decide to track this at Vulcan API level. However, for me it's not clear if we are going to use the same table. Let's discuss this in a future discussion.

2021-04-15 06:20 UTC, ka3de approved these changes
LGTM.

2021-04-15 16:13 UTC, merged