Fine tune Kafka implementation
adevinta/vulcan-api pull request #98
Opened 2022-12-12 15:10 UTC by ka3de

This PR fine tunes a couple of minor points in regards of the Kafka implementation:

- Kafka client push: Avoids the client to be able to block for ever waiting for a message delivery confirmation.
- Kafka test utils:
  - Improves randomization of topic names generation in order to avoid collisions during tests [due to non atomic create/delete topics methods]
  - Fixes infinite loop when trying to create a topic which already exists. Returns error instead.

2022-12-13 11:27 UTC, manelmontilla requested changes

2022-12-13 11:27 UTC, manelmontilla commented on pkg/asyncapi/kafka/client.go
> +	case <-time.After(maxDeliveryWait):
This was coded in this way on purpose, the thing is, let's suppose that it takes more than 30 seconds, that initially sounds a good amount of time, to receive the confirmation from Kafka that a message was committed. Then we will consider this message as not delivered and retry again. It is true that, because how the code using this client works, we will just send the send the same message again, which is acceptable in our case, but nevertheless I think it is better to leave the Kafka go to deal with possible timeouts.

2022-12-13 11:27 UTC, manelmontilla commented on pkg/testutil/kafka.go
> +			return fmt.Errorf("error creating topics: topic already exists")
Unfortunately deleting topics in Kafka is [an asynchronous operation](https://github.com/confluentinc/confluent-kafka-python/issues/813#issuecomment-606843111)  that can take (and some times it takes!!) a quite a few time. For instance in my M1 ARM processor the docker image of Kafka was quite slow, so many times was having flaky tests because of this.

2022-12-13 11:27 UTC, manelmontilla commented on pkg/testutil/kafka.go
> +		name := strings.ToLower(fmt.Sprintf("%s_%s_%d_test", topic, parts[len(parts)-1], tRef))
Much better yes, thank you very much!!

2022-12-13 11:41 UTC, ka3de commented on pkg/asyncapi/kafka/client.go
> +	case <-time.After(maxDeliveryWait):
I'm not very familiar with go-kafka but I could not see an explicit TO definition in the library documentation, so not sure if we are accepting the risk of blocking the CDC goroutine for too long here.. But for me it's ok to revert this right now as it's still initial stages of the integration and analyze how it behaves.

2022-12-13 11:46 UTC, ka3de commented on pkg/testutil/kafka.go
> +			return fmt.Errorf("error creating topics: topic already exists")
Yep, and this was getting worse when wanting to create more than one topic, as one of them could be created in an initial iteration, but if the other one fails, in consecutive iterations we would be always hitting the "topic already exists" error for the first one which was already created. So the more topics you want to create, the most probable to be stuck for ever here.

2023-01-17 15:49 UTC, manelmontilla commented on pkg/testutil/kafka.go
> +			return fmt.Errorf("error creating topics: topic already exists")
Ok, now I'm getting what you say, it is true that know that the way of creating names for the test topics includes the time, it would be harder for us to get stuck here, but in any case I think we could fix this just by creating the topics one by one instead of all in batch, that way we can wait to be sure that each topic is for sure newly created.

2023-01-17 16:16 UTC, manelmontilla approved these changes
LGTM

2023-01-17 16:20 UTC, merged